[package]
name = "gategen"
version = "0.1.0"
edition = "2021"

[dependencies]
gateutil = { version="0.1.0", path="../gateutil" }
gate_calc_log_bits = { path="../gate_calc_log_bits", version="0.1.0" }
itoap = "1.0"
thiserror = "1.0"
generic-array = "0.14"
